### ISSUE TITLE
Can you add the demo downloaders

### ISSUE THREAD

**Issue by Smurf-IV** [Wagnerp/Krypton-NET-Version-Dashboard#1]
For both the Toolkit, and the extended ?

**Comment by PWagner1** [comment]
Yes I can.

**Comment by PWagner1** [comment]
Messing around with either DropBox or OneDrive

**Comment by Smurf-IV** [comment]
> 
> 
> Messing around with either DropBox or OneDrive

Not sure I understand, Why can they not just be referenced on the page, then go to the relevant "Releases" links ?

**Comment by Smurf-IV** [comment]
I see that you have added the Demo Downloaders, but they go to:

     https://github.com/Wagnerp/Krypton-NET-Version-Dashboard/blob/master

which is routed to a 404

**Comment by PWagner1** [comment]
Yes, that's in prep for the links that I'm going to put in. The nice thing about Dropbox is that you can upload files in windows explorer, and generate a public URL right from the context menu.

**Comment by PWagner1** [comment]
I've compiled a 'all-in-one' installer, but it's 1.5 GB!
